#!/usr/bin/perl
#
# notificacion
#
# 	Indica si hay notificaciones pendientes. La llamada es por ajax desde principales
# 2016-06-22. Ernesto - Versión 1.0


$::debug = 0;
($::debug) and print "Content-type:text/plain\n\n";


use strict;
use DBI;
use CGI qw/:standard/;
#use utf8;
use CGI::Carp qw/fatalsToBrowser/;
use portal3 qw/getSession portal_url notifications/;


my ($userid,$sessionid,$dependid,$lugarid) = getSession(cookie(-name=>'SESION'));

print header(-charset=>'utf-8');
print (notifications($userid) ? 1 : 0);

exit(0);

